apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
  - name: nginx
    image: nginx:1.16.1
---
apiVersion: v1
kind: Pod
metadata:
  name: experiment
  labels:
    app: experiment
spec:
  containers:
  - name: nginx
    image: nginx
