apiVersion: v1
kind: ConfigMap
metadata:
  name: consistent-sharding-config
data:
  nginx.conf: |
    worker_processes 5;
    worker_rlimit_nofile 8192;
    events {
      worker_connections 1024;
    }

    http {
      # define a named 'backend' that we can use in the proxy directive # below.
      upstream backend {
        # Has the full URI of the request and use a consistent hash hash $request_uri consistent
        server web-shard-0.web-service;
        server web-shard-1.web-service;
        server web-shard-2.web-service;
      }

      server {
        listen 80;
        location / {
          proxy_pass http://backend;
        }
      }
    }