apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-shard
spec:
  selector:
    matchLabels:
      app: web
  serviceName: "web-service"
  replicas: 3
  template:
    metadata:
      labels:
        app: web
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: web
        image: nginx